[build-system]
# Minimum requirements for the build system to execute.
# TODO: We should look at SciPy and set mins for these like they do
requires = [
    # Changes here need to be reflected in cibw_before_build_windows.sh
    "setuptools>=68.0.0",
    "wheel>=0.37.0",
    "numpy>=2.0.0rc1,<3",
]

[tool.cibuildwheel]
# 3.9 is the only wheel NumPy ships for PyPy as of 2023/01/29
skip = "cp36-* cp37-* cp38-* *-manylinux_i686 *_ppc64le *_s390x *-musllinux* *-win32 pp37* pp38* pp310* pp*-win_*"
build-verbosity = 3
before-all = "bash {project}/build_tools/cibw_before_all.sh {project}"
# pytest 8.0: https://github.com/pytest-dev/pytest/issues/11884
test-requires = [
    "pytest!=8.0.0,!=8.0.1,!=8.0.2,!=8.1.1,!=8.1.2,!=8.2.0;platform_system=='Windows'",
    "pytest;platform_system!='Windows'",
    "threadpoolctl",
]
test-command = "bash {project}/build_tools/cibw_test_command.sh {project}"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
repair-wheel-command = "auditwheel show {wheel} && auditwheel repair -w {dest_dir} {wheel}"
environment-pass = ["RUNNER_OS"]
environment = { OPENMEEG_LIB="../../install/lib64", OPENMEEG_INCLUDE="../../install/include/OpenMEEG", OPENMEEG_USE_SWIG="1", OPENBLAS_INCLUDE="/usr/local/include" }

[tool.cibuildwheel.macos]
archs = "x86_64 arm64"
test-skip = "*_arm64"
repair-wheel-command = "bash $GITHUB_WORKSPACE/build_tools/cibw_repair_wheel_command_macos.sh {delocate_archs} {dest_dir} {wheel}"
environment = { OPENMEEG_LIB="../../install/lib", OPENMEEG_INCLUDE="../../install/include/OpenMEEG", OPENMEEG_USE_SWIG="1", OPENBLAS_INCLUDE="/usr/local/include" }

[tool.cibuildwheel.windows]
before-build = "bash {project}/build_tools/cibw_before_build_windows.sh {project}"
repair-wheel-command = "bash %GITHUB_WORKSPACE%/build_tools/cibw_repair_wheel_command_windows.sh {dest_dir} {wheel}"
environment = { OPENMEEG_USE_SWIG="0" }

[tool.ruff]
select = ["E", "F", "W", "D", "I"]
exclude = ["__init__.py", "setup.py"]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D413", # Missing blank line after last section
]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"*/tests/*.py" = [
    "D103", # Missing docstring in public function
]
