[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "numpy",
]

[tool.cibuildwheel]
skip = "cp36-* *-manylinux_i686 *_ppc64le *_s390x *-musllinux* *-win32"
build-verbosity = "3"
before-build = "bash {project}/build_tools/cibuildwheel_before_build.sh {project}"
test-command = "python -c 'import openmeeg; print(openmeeg.sqr(4)); assert openmeeg.sqr(4) == 16'"
environment = { OPENMEEG_LIB="../../install/lib", OPENMEEG_INCLUDE="../../install/include/OpenMEEG", OPENMEEG_USE_SWIG="1" }

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_24"
manylinux-aarch64-image = "manylinux_2_24"

[tool.cibuildwheel.macos]
archs = "x86_64 arm64"
test-skip = "*_arm64"

[tool.cibuildwheel.windows]
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"
