os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

clone_folder: C:\projects\openmeeg

platform: x64
configuration: Release

install:
  - "SET PATH=C:\\Miniconda-x64;C:\\Miniconda-x64\\Scripts;%PATH%"
  # by default, all script lines are interpreted as batch
  - cinst -y swig
  - "conda update -y conda"
  - "conda install -y numpy" # numpy installs mkl2017 !

environment:
  matrix:
    - lapack: OpenBLAS
      vtk: ON
      python: ON
    - lapack: LAPACK
      vtk: OFF
      python: OFF

matrix:
  fast_finish: true

build_script:
  - echo Running cmake...
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_SHARED=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING:BOOL=ON -DENABLE_PACKAGING:BOOL=ON -DCMAKE_SKIP_RPATH:BOOL=OFF -DENABLE_PYTHON=%python% -DBLASLAPACK_IMPLEMENTATION=%lapack% -DUSE_VTK=%vtk% ..
  - cmake --build . --config Release

after_build:
  - cpack
  - cpack -G TGZ

before_test:
  - echo Running tests...
  - cd C:\projects\openmeeg\build\OpenMEEG\build
    # needed to find the dlls (VTK, (OpenBLAS, mingw), MKL)
  - setPATH.cmd
  - echo %PATH%
  - ctest -V

artifacts:
  - path: build\OpenMEEG-*.exe
    name: OpenMEEG-Win64.exe
  - path: build\OpenMEEG-*.tar.gz
    name: OpenMEEG-Win64.tar.gz

deploy:
  provider: FTP
  protocol: ftps
  host:
    secure: x1oONEbQPD9iOpA1uMRawiVBPCsp74PeQpzjINr3mEM=
  username:
    secure: fsdBnQNhKAfx97kcWRN0mw==
  password:
    secure: y5kbt9kB0gNeeBrDF0Q1V4itUlnOp1XfD9MlepKQkEE=
  folder:
    secure: u9s4t7Uj0Oucd5k05tO3zGdBvhzatzETNZOgG9JnNP4yT6lwjJTlv89M8G3CxM8S
  artifact: OpenMEEG-Win64.exe OpenMEEG-Win64.tar.gz

