shallow_clone: true

platform:
  # - x86
  - x64

configuration:
  # - Debug
  - Release

image:
  - Visual Studio 2015
  # - Visual Studio 2017

cache:
  - C:\cmake-3.10.1-win64-x64
  - C:\w_mkl_2018.0.124.exe

environment:
  global:
      PYTHON: "C:\\conda"
      deploy_host:
        secure: elpy2/txkSJRwksSCwLehfm3eLDYTAalGUvTGzPlphY=
      deploy_user:
        secure: 2kJCgcedzNy4rFCQbW7PNw==
      deploy_password:
        secure: Cr908GItsFT5Wp0rYB8ExUukZxSu+mgdprFvU4CxmcM=
      deploy_folder:
        secure: k+J4yytvUwuRb5wHVAetZ84O90bJ4ZgwYOS9vLec90o09HP+GLvD9DvNbG1q9Q2p

  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PACK: ON

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

# # To allow remote connection to appveyor
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  ############################################################################
  # Install Conda
  ############################################################################
  - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  ############################################################################
  # Install Conda
  ############################################################################
  - conda config --add channels conda-forge
  - conda install cmake openblas=0.2.20 libmatio=1.5.12 toolchain swig numpy
  - set LIBRARY_LIB=C:\conda\Library\lib
  - copy /y %LIBRARY_LIB%\zlibstatic.lib %LIBRARY_LIB%\z.lib
  
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: |
      mkdir build
      cd build

  - ps: $env:CMAKE_PREFIX_PATH='C:\conda\Library\'
  - ps: $env:INSTALL_DIR='C:\fake_install_dir\'
  # - ps: $env:VCOMP_PATH="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/redist/x64/Microsoft.VC140.OpenMP/vcomp140.dll"
  - cmmd: set CONFIGURATION="Release"
  - cmmd: set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\build\simulate_install_dir
  - cmmd: set MY_CONDA_PATH=%CMAKE_PREFIX_PATH%
  - cmmd: set CMAKE_CONFIG=%CONFIGURATION%

  - cmake -G "Visual Studio 14 2015 Win64"   ^
      -DCMAKE_CXX_STANDARD=11                ^
      -DBLA_VENDOR=OpenBLAS                  ^
      -DENABLE_PYTHON=ON                     ^
      -DBLA_STATIC=OFF                       ^
      -DCMAKE_PREFIX_PATH=%MY_CONDA_PATH%    ^
      -DCMAKE_VERBOSE_MAKEFILE=ON            ^
      -DBUILD_DOCUMENTATION=OFF              ^
      -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR%   ^
      -DVCOMP_WORKAROUND=ON                  ^
      %APPVEYOR_BUILD_FOLDER%                     

  - appveyor PushArtifact C:\projects\openmeeg\build\cmake_install.cmake

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --target install --config %CONFIGURATION% 

# test_script:
#   # Copy runtime libs for testing
#   - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\tests\%CONFIGURATION%\
#   - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\apps\%CONFIGURATION%\
#   - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\apps\tools\%CONFIGURATION%\

#   - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG\%CONFIGURATION%\OpenMEEG.dll %APPVEYOR_BUILD_FOLDER%\build\apps\%CONFIGURATION%\
#   - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG\%CONFIGURATION%\OpenMEEG.dll %APPVEYOR_BUILD_FOLDER%\build\apps\tools\%CONFIGURATION%\

  # Check dependencies
  - depends.exe /f:1 /c /oc:c:\projects\depends-testvector.txt %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\tests\%CONFIGURATION%\OpenMEEGMathsTest-vector.exe
  - depends.exe /f:1 /c /oc:c:\projects\depends-omassemble.txt %APPVEYOR_BUILD_FOLDER%\build\apps\%CONFIGURATION%\om_assemble.exe
  - appveyor PushArtifact C:\projects\depends-testvector.txt
  - appveyor PushArtifact C:\projects\depends-omassemble.txt

#   # Test
#   - cmd: ctest -v .

on_success:

deploy: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
