shallow_clone: true

platform:
  # - x86
  - x64

configuration:
  # - Debug
  - Release

image:
  - Visual Studio 2019
  #- Visual Studio 2015

cache:
  - C:\cmake-3.10.1-win64-x64
  - C:\w_mkl_2018.0.124.exe

environment:
  global:
      PYTHON: "C:\\conda"
      deploy_host:
        secure: elpy2/txkSJRwksSCwLehfm3eLDYTAalGUvTGzPlphY=
      deploy_user:
        secure: 2kJCgcedzNy4rFCQbW7PNw==
      deploy_password:
        secure: Cr908GItsFT5Wp0rYB8ExUukZxSu+mgdprFvU4CxmcM=
      deploy_folder:
        secure: k+J4yytvUwuRb5wHVAetZ84O90bJ4ZgwYOS9vLec90o09HP+GLvD9DvNbG1q9Q2p

  matrix:
    - BLAS_VERSION: Intel10_64lp_seq
      BUILD_STATIC : ON
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PACK: ON

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/


# ## To allow remote connection to appveyor
# ## connect via rdp using:
# #    $ xfreerdp /d:domain /u:appveyor /p:'password' /cert-ignore /v:ipaddr:port
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  ############################################################################
  # Install Win packages
  ############################################################################
  - choco install dependencywalker -y --allow-empty-checksums


  ############################################################################
  # Install Conda
  ############################################################################
  - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - CALL "%PYTHON%\\Scripts\\activate.bat"

  ############################################################################
  # Install CMake
  ############################################################################
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.10.1-win64-x64\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.10/cmake-3.10.1-win64-x64.zip'
        7z x -y cmake-3.10.1-win64-x64.zip -oC:\
      }
      $env:PATH="C:\cmake-3.10.1-win64-x64\bin;$env:PATH"

  ############################################################################
  # Install MKL
  ############################################################################
  - ps: |
      if (![IO.File]::Exists("C:\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe does not exist. Preparing to download MKL ..'
        Start-FileDownload 'http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12079/w_mkl_2018.0.124.exe' -FileName 'C:\w_mkl_2018.0.124.exe'
        ECHO 'Done'
      }
      C:\w_mkl_2018.0.124.exe -s -l c:\logs\extract-mkl.log -a install --eula=accept --components=all --output='C:\logs\install-mkl-output.txt' --installdir='C:\Program Files (x86)\IntelSWTools' --log='c:\logs\install-mkl.log' | Out-Null
      $env:LD_MKL_PATH='C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.0.124\windows\mkl\lib\intel64_win\'
      $env:LIB="$env:LD_MKL_PATH;$env:LIB"

  ############################################################################
  # Install Conda
  ############################################################################
  - conda config --add channels conda-forge
  - conda install --yes -c massich matio-cmake
  - set LIBRARY_LIB=C:\conda\Library\lib
  - copy /y %LIBRARY_LIB%\zlibstatic.lib %LIBRARY_LIB%\z.lib
  # force to pick zlibstatic in order to create proper wheels
  
before_build:
  - call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.0.124\windows\bin\compilervars_arch.bat" intel64 vs2019
  - call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.0.124\windows\mkl\bin\mklvars.bat" intel64
  - "ECHO %MKLROOT%"
  - cd %APPVEYOR_BUILD_FOLDER%
  - "ECHO %BLAS_VERSION%"
  - "ECHO 'cmake -DBLA_STATIC=%BUILD_STATIC% -DBLA_VENDOR=%BLAS_VERSION% -G \"Visual Studio 16 2019 Win64\" .. '"
  - cmake --version
  - "ECHO 'MKLROOT is %MKLROOT%'"
  - ps: |
      mkdir build
      cd build
  - ps: $env:matio_dir='C:\conda\Library\'
  - ps: $env:CMAKE_PREFIX_PATH='C:\conda\Library\cmake'
  - ps: $env:INSTALL_DIR='C:\fake_install_dir\'
  # - ps: $env:VCOMP_PATH="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/redist/x64/Microsoft.VC140.OpenMP/vcomp140.dll"
  - cmake -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR%   ^
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%     ^
          -DBLA_STATIC=%BUILD_STATIC%            ^
          -DBLA_VENDOR=%BLAS_VERSION%            ^
          -DVCOMP_WORKAROUND=ON                  ^
          -G "Visual Studio 16 2019 Win64" ..
  - appveyor PushArtifact C:\projects\openmeeg\build\cmake_install.cmake

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target install
  - cpack -C %CONFIGURATION%
  - cpack -C %CONFIGURATION% -G NSIS

test_script:
  # Copy runtime libs for testing
  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\tests\%CONFIGURATION%\
  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\apps\%CONFIGURATION%\
  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\apps\tools\%CONFIGURATION%\
  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\%CONFIGURATION%\OpenMEEGMaths.dll %APPVEYOR_BUILD_FOLDER%\build\tests\%CONFIGURATION%\

  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG\%CONFIGURATION%\OpenMEEG.dll %APPVEYOR_BUILD_FOLDER%\build\apps\%CONFIGURATION%\
  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG\%CONFIGURATION%\OpenMEEG.dll %APPVEYOR_BUILD_FOLDER%\build\apps\tools\%CONFIGURATION%\
  - cp %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG\%CONFIGURATION%\OpenMEEG.dll %APPVEYOR_BUILD_FOLDER%\build\tests\%CONFIGURATION%\

  # Check dependencies
  - depends.exe /f:1 /c /oc:c:\projects\depends-testvector.txt %APPVEYOR_BUILD_FOLDER%\build\OpenMEEGMaths\tests\%CONFIGURATION%\OpenMEEGMathsTest-vector.exe
  - depends.exe /f:1 /c /oc:c:\projects\depends-omassemble.txt %APPVEYOR_BUILD_FOLDER%\build\apps\%CONFIGURATION%\om_assemble.exe
  - appveyor PushArtifact C:\projects\depends-testvector.txt
  - appveyor PushArtifact C:\projects\depends-omassemble.txt

  # Test
  - call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.0.124\windows\mkl\bin\mklvars.bat" intel64
  - cmd: ctest --build-config %CONFIGURATION% -v .

on_success:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG-2.4.9999-Win64.tar.gz

  - conda create -n packageenv --yes pip python=2.7
  - activate packageenv
  - conda install -y --quiet paramiko
  - conda install -y --quiet pyopenssl
  - set src_dir=%APPVEYOR_BUILD_FOLDER%
  - cd %src_dir%
  - if NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER (if %APPVEYOR_REPO_BRANCH% == master ( if %pack%==ON ( python %APPVEYOR_BUILD_FOLDER%\build_tools\upload_package_gforge.py %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG-*.exe %APPVEYOR_BUILD_FOLDER%\build\OpenMEEG-*.gz) ))

deploy: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
