extraction:
  cpp:
    prepare:
      packages:
        - libopenblas-dev
        - liblapacke-dev # XXX: If lapacke is missing, cmake does not break at generation but at compilation.

    configure:
      command:
        - mkdir -p _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBLA_VENDOR=OpenBLAS ..

    index:
      build_command:
        - cd _lgtm_build_dir
        - make

path_classifiers:
  library:
    - doxy2swig.py
