language: erlang
install:
  - sudo apt-get update
  - sudo apt-get install doxygen python-numpy swig python-dev libatlas-base-dev libtiff4-dev
  - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
  - tar -xzf cmake-3.0.2-Linux-64.tar.gz
  - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
  - rm -rf cmake-3.0.2-Linux-64
  - rm cmake-3.0.2-Linux-64.tar.gz
  - mkdir build; cd build; cmake
              -DATLAS_INCLUDE_PATH:PATH=/usr/include/atlas
              -DBUILD_SHARED:BOOL=ON
              -DBUILD_TESTING:BOOL=ON
              -DPYTHON_WRAP:BOOL=ON
              -DUSE_VTK:BOOL=OFF
              -DUSE_ATLAS:BOOL=ON
              -DUSE_SYSTEM_zlib:BOOL=OFF
              -DUSE_SYSTEM_hdf5:BOOL=OFF
              -DUSE_SYSTEM_matio:BOOL=OFF
              -DCMAKE_SKIP_RPATH:BOOL=OFF
              ..
  - make
script:
  - make check
