language: cpp
sudo: required
dist: trusty
osx_image: xcode7.3
matrix:
  include:
    - os: linux  # packaged version (no python, no vtk, with static MKL)
    - os: osx  # test brew full package (without project)

script:
   - echo "good"

after_success:
   - mkdir -p /tmp/xx/ && cd /tmp/xx/
   # # - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
   - MESSAGE="[av skip] Push from try branch of openmeeg $(date)"
   - git clone git://${GH_REPO}
   - cd ${REPO}
   # - git config user.email ${EMAIL}
   # - git config user.name ${USER}
   - git config user.email "openmeeg@openmeeg.org"
   - git config user.name "openmeeg"
   - |
    function gitpush() {
       git fetch origin
       git reset --hard origin/master
       # cp -R ${PACKAGE_DEPLOY} ./
       echo "- $(date)" >> README.md
       git add ${FILES}
       git add OpenMEEG*.tar.gz
       git status
       git commit -m "${MESSAGE}"
       git pull --no-edit "https://${OPENMEEG_PACKAGING_TOKEN}@${GH_REPO}" master
       git push "https://${OPENMEEG_PACKAGING_TOKEN}@${GH_REPO}" master
     }
     travis_retry gitpush

notifications:
  email: false

env:
  global:
    - CONFIGURATION=Release
    - PYTHON_VERSION=3.6
    - USER="openmeeg"
    - REPO="openmeeg_packages"
    - FILES="README.md"
    - GH_REPO="github.com/${USER}/${REPO}.git"
    - secure: KPHv7A0gp+NNaj3oMeemI5Wt60Xlyc2XTr+zV4pxQmgoHTLA3c+8f+ZWCfF59pI/cmGhV0zG6noshOhXoPzS31fVIgpP1CHvpj2T16NOboM7G6lBpIBvncJ+a3BfzUUiLgPGlQYZRNeIATYl6shLaXP4FG8Nqt1O1TcE73M7Ba0=
