language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - USE_SYSTEM=1
        - USE_PROJECT=1
        - USE_CGAL=1
        - USE_VTK=1
       #- BLASLAPACK_IMPLEMENTATION=Auto (not specifying is the same as Auto)
    - os: osx
      compiler: clang
      env:
        - USE_SYSTEM=1
        - USE_PROJECT=1
        - BLASLAPACK_IMPLEMENTATION=vecLib
        - BUILD_DOCUMENTATION=1
    - os: osx
      compiler: clang
      env:
        - USE_PROJECT=0
        - BLASLAPACK_IMPLEMENTATION=Auto # (Auto is the same as MKL/OpenBLAS/vecLib in priority)
    - os: linux
      compiler: clang
      env:
        - USE_SYSTEM=1
        - USE_PROJECT=1
        - BUILD_DOCUMENTATION=1
        - BLASLAPACK_IMPLEMENTATION=LAPACK
    - os: linux
      compiler: gcc
      env:
        - USE_SYSTEM=1
        - USE_PROJECT=1
        - USE_CGAL=1
        - USE_VTK=1
        - USE_COVERAGE=1
    - os: linux
      compiler: gcc
      env:
        - USE_SYSTEM=0
        - USE_PROJECT=1
        - BLASLAPACK_IMPLEMENTATION=LAPACK
    - os: linux
      compiler: gcc
      env:
        - USE_PROJECT=0
        - USE_CGAL=1
        - USE_VTK=1
        - BLASLAPACK_IMPLEMENTATION=Atlas

before_install: source build_tools/travis/before_install.sh

install: source build_tools/travis/install.sh

script:
  - "$CXX --version"
  - if [[ "$USE_PROJECT" == "0" ]]; then make test; else make test-OpenMEEG; fi
  - cpack -G TGZ .

after_success:
  - source codecoverage.sh
  - scp *gz $deploy_user@$deploy_host:$deploy_path

env:
  global:
  - secure: THD5qh1lrYDL2dEYVu+pitC+RsfB/Wn8jJjNTVFYEwPnSw5zov4N2aVNwOaHM4qJwp8NdL81ke4gI0P9vS89HPSstsnkboAwzn8Kj3UhAq0X10vnkgH+BIjUut0H3DCcY0O5Y2/1pc5KL/6pErT6tdFlRq8xS6YwVe7UKx3rEXo=
  - secure: XBNTHU+DVCKeUKjxVSfvAkFr/KnvzYDDn28u8Y41v9kT+yHE1HHPnSYJS9JndQllOUAXtT0Ix81LSKG9MVthIWs5uPTOOg4hPZloE8mOYWSs/EHLraEEbZFUAaoCz2ZVYdA92HM1YAVo4Bi+zMy9g7Ra4POSWwFY5n/zV+ma//A=
  - secure: JlEdLh7nIcHVEmlsEkZkm2oYJUpQUt4OBe+Z8V0RNctcmax5VUNQ/GJoDQlZKsQNiM+kF9DH5W7wW3+IQas+ffEPU0lEcB/lhHaK91aOUzqPQ/GyTZm/0NABIrNDAvjnf4otcFb6meK+N22Ka/4xjvbiqGyTK8g9N+VEl8qHG3s=
