# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\openmeeg

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd C:\projects\openmeeg
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_SHARED=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING:BOOL=ON -DENABLE_PYTHON=OFF -DENABLE_PACKAGING:BOOL=OFF -DUSE_VTK=OFF -DUSE_ATLAS=OFF -DUSE_SYSTEM_matio:BOOL=OFF -DUSE_SYSTEM_hdf5:BOOL=OFF -DUSE_SYSTEM_zlib=OFF -DCMAKE_SKIP_RPATH:BOOL=OFF -DUSE_LAPACK=ON .
  - cmake --build . --config Release

# scripts to run after build
after_build:
  - 7z a libopenmeeg.zip c:\projects\openmeeg\OpenMEEG\install
  - echo CMake succeded

before_test:
  - echo Running tests...
  - cd C:\projects\openmeeg\OpenMEEG\build
  - ctest -V

after_test:
  - echo Tests succeded


artifacts:
  - path: libopenmeeg.zip
    name: libopenmeeg.zip
