os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

clone_folder: C:\projects\openmeeg

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build_script:
  - echo Running cmake...
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_SHARED=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING:BOOL=ON -DENABLE_PACKAGING:BOOL=ON -DCMAKE_SKIP_RPATH:BOOL=OFF -DENABLE_PYTHON=OFF -DBLASLAPACK_IMPLEMENTATION=LAPACK ..
  - cmake --build . --config Release

after_build:
  - cpack
  - cpack -G TGZ

before_test:
  - echo Running tests...
  - cd C:\projects\openmeeg\build\OpenMEEG\build
  - ctest -V

artifacts:
  - path: build\OpenMEEG-*-Win64-static.exe
    name: OpenMEEG-Win64.exe
  - path: build\OpenMEEG-*-Win64-static.tar.gz
    name: OpenMEEG-Win64.exe
