#!/usr/bin/env python3

import os
import sys
import time
import importlib

help = '''usage: om.py [-h] [assemble | minverser | gain | forward]

Main driver for various OpenMEEG operations.
For subcommand help use "om subcommand --help".

Subcommands:
  assemble    Contructs various EEG/MEG/ECoG/EIT basic matrices.
  minverser   Constructs the inverse of an head matrix.
  gain        Compute various leadfields (gain matrices).
  forward     Constructs the forward problem given a leadfield (gain matrix) and sources.

Options:
  -h, --help  show this help message and exit'''


if len(sys.argv)==1 or sys.argv[1]=='-h' or sys.argv[1]=='--help':
    print(help)
    sys.exit(1)

# If we are here, we know that the first argument must be a command.

subcommand = sys.argv[1]
if subcommand in ['assemble', 'minverser', 'gain', 'forward']:
    om_module = importlib.import_module(subcommand)
else:
    print('Wrong sub-command: '+subcommand)
    print(help)
    sys.exit(1)

subargv = sys.argv[2:]
subargv.insert(0,'openmeeg '+subcommand)
args = om_module.parse_arguments(subargv)
print(args)

print('-------------------------------------------')
print('Command line:')
print(*sys.argv)
print('-------------------------------------------')

start = time.time()

getattr(om_module,args.processing_function)(args)

end = time.time()

print('-------------------------------------------')
print('Elapsed Time: ', end - start, ' s.')
print('-------------------------------------------')
