MESSAGE("${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE_DIR}/${TEST_RESULT}")
EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE_DIR}/${TEST_RESULT}
                RESULT_VARIABLE OUTPUT_COMPARE)

IF (${OUTPUT_COMPARE} STREQUAL "0")
        MESSAGE("Success")
        EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_OUTPUT})
        RETURN()
ENDIF()

MESSAGE("FAILURE")
