EXECUTE_PROCESS(COMMAND ${TEST_PROGRAM} ${TEST_ARGS}
		        RESULT_VARIABLE RESULT
                OUTPUT_FILE     ${TEST_OUTPUT})
#                OUTPUT_ERROR    ERROR)

EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE}
                RESULT_VARIABLE RESULT_COMPARE)

MESSAGE("Result " ${RESULT})
MESSAGE("Result:" ${RESULT_COMPARE})

IF (${RESULT} STREQUAL "0" AND ${RESULT_COMPARE} STREQUAL "0")
    MESSAGE("Success")
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_OUTPUT})
ELSE()
    MESSAGE("FAILURE")
ENDIF()
