SET(TEST_OUTPUT ${TEST_DIR}/${TEST_NAME}.out)

EXECUTE_PROCESS(COMMAND ${TEST_PROGRAM} ${TEST_ARGS}
		        RESULT_VARIABLE RESULT
                OUTPUT_FILE     ${TEST_OUTPUT})
#                OUTPUT_ERROR    ERROR)

IF (${RESULT} STREQUAL "0")
    MESSAGE("${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE_DIR}/${OUTPUT}")
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_OUTPUT} ${TEST_REFERENCE_DIR}/${OUTPUT}
                    RESULT_VARIABLE OUTPUT_COMPARE)

    MESSAGE(${OUTPUT_COMPARE})
    IF (${OUTPUT_COMPARE} STREQUAL "0")
        EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E compare_files ${TEST_RESULT} ${TEST_REFERENCE_DIR}/${TEST_RESULT}
                        RESULT_VARIABLE RESULT_COMPARE)

#        IF (${RESULT_COMPARE} STREQUAL "0")
            MESSAGE("Success")
            EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E remove ${TEST_OUTPUT} ${TEST_RESULT})
            RETURN()
#        ENDIF()

    ENDIF()
ENDIF()

MESSAGE("FAILURE")
