include(UseOpenMP)
include(UseVTK)
include(UseGifti)
include(UseCGAL)
include(ProgressBar)
include(BlasLapackOption)

option(BUILD_TOOLS "Build tools" ON)
option(BUILD_TESTING "Build the testing tree" ON)
option(BUILD_DOCUMENTATION "Build the Doxygen documentation" OFF)
option(BUILD_TUTORIALS "Build Tutorials" OFF)
option(ENABLE_PYTHON "Enable Python Wrapping" OFF)
option(ENABLE_COVERAGE "Enable Coverage" OFF)
