MACRO(SET_FILE_PROPERTIES PROPERTY)
    FOREACH(arg ${ARGN})
        STRING(REGEX REPLACE "^([^ ]+) .+$" "\\1" VAR_NAME ${arg})
        STRING(REGEX REPLACE "^[^ ]+ +(.+)$" "\\1" VALUE ${arg})
        STRING(REGEX REPLACE ":" ";" VALUE ${VALUE})
        SET(${PROPERTY}_${VAR_NAME} "${VALUE}")
    ENDFOREACH()
ENDMACRO()

FUNCTION(OPENMEEG_COMPARISON_TEST SUBJECT TEST_NAME MODIFIER COMPARISON_COMMAND FILENAME REFERENCE_FILENAME)
    #SET(FILENAME ${SUBJECT}${Suffix_${TEST_NAME}})
    SET(FILENAME ${OpenMEEG_BINARY_DIR}/tests/${FILENAME})
    SET(REFERENCE_FILENAME ${OpenMEEG_SOURCE_DIR}/tests/${REFERENCE_FILENAME})
    SET(COMPARISON_PARAMETERS ${CompareOptions_${TEST_NAME}})

    IF (WIN32)
        SET(COMPARISON_COMMAND "${EXECUTABLE_OUTPUT_PATH}/${COMPARISON_COMMAND})
    ELSE()
        SET(COMPARISON_COMMAND "${CMAKE_CURRENT_BINARY_DIR}/${COMPARISON_COMMAND})
    ENDIF()

    ADD_TEST("compare-${TEST_NAME}-${SUBJECT}${MODIFIER}" 
        ${COMPARISON_COMMAND} ${FILENAME} ${REFERENCE_FILENAME} ${COMPARISON_PARAMETERS} ${ARGN})
ENDFUNCTION()
