MACRO(GENERATE_VERSION_INFO )
    SET(VERSION_STRING "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
    IF (${CPACK_PACKAGE_VERSION_PATCH} STREQUAL "svn")
        SET(REVISION_NUMBER STRING(REGEX REPLACE "$Revision: \(.*\)$" "(\1)" REVISION_NUMBER "$Revision$")
    ENDIF
ENDMACRO()
