name: Test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash -el {0}

jobs:

  build:
    continue-on-error: true
    strategy:
      matrix:
        # Currently, VTK is only installed+tested on Ubuntu
        # Someday we could use OpenBLAS for Windows once vcpkg sorts things out
        # (https://github.com/microsoft/vcpkg/issues/25176), but it's unclear
        # if this will really help anything. SciPy's should be well tested
        # already.
        #os: [ubuntu-20.04, windows-2019, macos-latest]
        os: [windows-2019]
        blas: [OpenBLAS]
        blas_linking: [dynamic]
        python: [python]
        windows_compiler: [mingw64]
        include:
        ## MSVC + MKL + static + Python
        #- os: windows-2019
        #  blas: mkl-findblas
        #  blas_linking: static
        #  python: python
        #  windows_compiler: msvc
        # MSVC + OpenBLAS + Python
        - os: windows-2019
          blas: OpenBLAS
          blas_linking: dynamic
          python: python
          windows_compiler: msvc
        ## MKL on each OS (static unless it has to be dynamic)
        #- os: windows-2019
        #  blas: mkl-findblas
        #  blas_linking: static
        #  python: python
        #  windows_compiler: mingw64
        #- os: ubuntu-20.04
        #  blas: mkl-findblas
        #  blas_linking: dynamic
        #  python: python
        #  windows_compiler: mingw64
        #- os: macos-latest
        #  blas: mkl-findblas
        #  blas_linking: static
        #  python: python
        #  windows_compiler: mingw64
        # ubuntu-18.04 build, but Python tests currently fail so use no-python
        #- os: ubuntu-18.04
        #  blas: OpenBLAS
        #  blas_linking: dynamic
        #  python: no-python
        #  windows_compiler: mingw64
        # Windows static build
        #- os: windows-2019
        #  blas: OpenBLAS
        #  blas_linking: static
        #  python: python
        #  windows_compiler: mingw64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Environment variables
      run: |
        if [[ "${{matrix.blas_linking}}" == 'static' ]]; then
          echo "Enabling static BLAS"
          echo "BLA_STATIC_OPT=-DBLA_STATIC=ON" >> $GITHUB_ENV
        fi
        if [[ "${{matrix.python}}" == 'python' ]]; then
          echo "Enabling Python"
          echo "PYTHON_OPT=-DENABLE_PYTHON=ON" >> $GITHUB_ENV
        fi
        if [[ "${{matrix.blas}}" == 'mkl'* ]]; then
          echo "Setting BLA_IMPLEMENTATION=${{matrix.blas}}"
          echo "BLA_IMPL=-DBLA_IMPLEMENTATION=${{matrix.blas}}" >> $GITHUB_ENV
        fi
        # Build docs on Ubuntu, not elsewhere (for speed)
        if [[ "${{matrix.os}}" == 'ubuntu'* ]]; then
          BUILD_DOCS=ON
        else
          BUILD_DOCS=OFF
        fi
        # Use -Werror on Windows and macOS, eventually should use on Linux
        if [[ ${{matrix.os}} != 'ubuntu*' ]]; then
          WERROR_OPT="-DENABLE_WERROR=OFF"
        else
          WERROR_OPT="-DENABLE_WERROR=ON"
        fi
        echo "Using WERROR_OPT=$WERROR_OPT"
        echo "WERROR_OPT=$WERROR_OPT" >> $GITHUB_ENV
        echo "Using DOC_OPT=$DOC_OPT"
        echo "DOC_OPT=-DBUILD_DOCUMENTATION=$BUILD_DOCS" >> $GITHUB_ENV

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.os }}

    # Always use conda for Python
    - name: Python via conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: "test"
        python-version: "3.10"
        channels: conda-forge
        channel-priority: strict

    - name: Python packages
      if: startswith(matrix.python, 'python')
      run: |
        pip install --upgrade -q pip
        if [[ ${{matrix.os}} == 'windows'* ]]; then
          EXTRA_PIP=delvewheel
        elif [[ ${{matrix.os}} == 'macos'* ]]; then
          EXTRA_PIP=delocate
        else
          EXTRA_PIP=auditwheel
        fi
        pip install --upgrade --progress-bar off -q numpy setuptools wheel twine $EXTRA_PIP
        # Fix Miniconda paths
        echo "PYTHON_INFO_OPT=-DPython3_EXECUTABLE=$(which python)" >> $GITHUB_ENV

    - name: MKL setup - mkl via conda
      if: startswith(matrix.blas,'mkl')
      run: |
        # To get a local testing env, you can do for example:
        # $ conda create -n openmeeg-mkl -c conda-forge --strict-channel-priority mkl-devel swig libmatio hdf5 numpy
        # $ conda activate openmeeg-mkl
        #
        # On Windows, locally this static build almost works:
        # ./build_tools/cmake_configure.sh -DBLA_IMPLEMENTATION=mkl-findblas -DBLA_STATIC=ON -DCMAKE_PREFIX_PATH="$CONDA_PREFIX/Library" -DCMAKE_CXX_FLAGS="-I$CONDA_PREFIX/Library/include" -DENABLE_PYTHON=ON
        # cmake --build build --config Release
        #
        # On Linux, locally this works:
        # ./build_tools/cmake_configure.sh -DBLA_IMPLEMENTATION=mkl-findblas -DCMAKE_PREFIX_PATH="$CONDA_PREFIX/lib" -DCMAKE_CXX_FLAGS="-I$CONDA_PREFIX/include" -DENABLE_PYTHON=ON
        # cmake --build build --config Release
        # cd build && LD_PRELOAD=$CONDA_PREFIX/lib/libmkl_rt.so ctest -C Release
        #
        conda install -c conda-forge -q mkl-devel
        if [[ "${{matrix.os}}" == 'windows'* ]]; then
          echo "CMAKE_PREFIX_PATH=$(cygpath -m $CONDA_PREFIX/Library)" >> $GITHUB_ENV
          echo "CMAKE_CXX_FLAGS=-I$(cygpath -m $CONDA_PREFIX/Library/include) ${CMAKE_CXX_FLAGS}" >> $GITHUB_ENV
        else
          echo "CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib" >> $GITHUB_ENV
          echo "CMAKE_CXX_FLAGS=-I$CONDA_PREFIX/include ${CMAKE_CXX_FLAGS}" >> $GITHUB_ENV
          if [[ "${{matrix.os}}" == 'ubuntu'* ]]; then
            echo "LD_PRELOAD=$CONDA_PREFIX/lib/libmkl_rt.so" >> $GITHUB_ENV
          fi
        fi

    - name: Windows 1 - cache vcpkg
      if: startswith(matrix.os,'windows')
      uses: actions/cache@v3
      with:
        path: |
          vcpkg
          build/vcpkg_installed
        key: vcpkg-${{ hashFiles('**/vcpkg.json') }}-${{ matrix.windows_compiler }}-0

    - name: Windows 2 - hdf5 and libmatio via vcpkg
      if: startsWith(matrix.os,'windows')
      id: runvcpkg
      run: |
        if [[ "${{ matrix.windows_compiler }}" == "mingw64" ]]; then
          export VCPKG_DEFAULT_TRIPLET="x64-mingw-dynamic"
        else
          export VCPKG_DEFAULT_TRIPLET="x64-windows"
          export CMAKE_GENERATOR="Visual Studio 16 2019"
        fi
        source ./build_tools/setup_windows_compilation.sh
        # On Windows, we tell cmake to copy all runtime deps to the build dir,
        # and for tests (and Python) to find them, we need to add it to PATH
        echo "PATH=$(cygpath -w ${PWD}/build);$PATH" >> $GITHUB_ENV

    - name: Windows 3 - OpenBLAS via MacPython download
      if: startsWith(matrix.blas,'OpenBLAS') && startsWith(matrix.os,'windows')
      run: |
        # OpenBLAS direct download (too slow to build using vcpkg)
        # and renaming to match what cmake wants to see
        curl -LO https://anaconda.org/multibuild-wheels-staging/openblas-libs/v0.3.18/download/openblas-v0.3.18-win_amd64-gcc_8_1_0.zip
        unzip openblas-v0.3.18-win_amd64-gcc_8_1_0.zip -d openblas
        OPENBLAS_LIB=${PWD}/openblas/64/lib
        OPENBLAS_INCLUDE=${PWD}/openblas/64/include
        echo "$OPENBLAS_LIB"
        test -d "$OPENBLAS_LIB"
        echo "$OPENBLAS_INCLUDE"
        test -d "$OPENBLAS_INCLUDE"
        pushd $OPENBLAS_LIB
        ls -al
        # TODO: This conditional should work but it does not...
        # if [[ "${{ matrix.blas_linking }}" != "static" ]]; then
        cp ../bin/libopenblas_v0.3.18-gcc_8_1_0.dll .
        cp libopenblas_v0.3.18-gcc_8_1_0.dll openblas.dll
        mv libopenblas_v0.3.18-gcc_8_1_0.dll.a openblas.dll.a
        # fi
        mv libopenblas_v0.3.18-gcc_8_1_0.a openblas.a
        mv libopenblas_v0.3.18-gcc_8_1_0.def openblas.def
        mv libopenblas_v0.3.18-gcc_8_1_0.exp openblas.exp
        mv libopenblas_v0.3.18-gcc_8_1_0.lib openblas.lib
        popd
        echo "OPENBLAS_LIB=$OPENBLAS_LIB" >> $GITHUB_ENV
        echo "LIB=$(cygpath -w $OPENBLAS_LIB);${LIB}" >> $GITHUB_ENV
        echo "CMAKE_CXX_FLAGS=-I$(cygpath -m $OPENBLAS_INCLUDE)" >> $GITHUB_ENV

    - name: Windows 4 - OpenBLAS needs Windows 8.1 SDK
      if: startsWith(matrix.blas,'OpenBLAS') && startsWith(matrix.os,'windows') && startsWith(matrix.windows_compiler,'msvc')
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"

    - name: macOS - hdf5, libmatio, and (optionally) OpenBLAS via brew
      if: startswith(matrix.os,'macos')
      run: |
        brew update > /dev/null
        if [[ "${{matrix.blas}}" == "OpenBLAS" ]]; then
          BREW_EXTRA=openblas
        fi
        brew install hdf5 libmatio boost swig $BREW_EXTRA
        if [[ "${{matrix.blas}}" == "OpenBLAS" ]]; then
          BLAS_DIR=/usr/local/opt/openblas
          echo "Checking for $BLAS_DIR/include"
          test -d $BLAS_DIR/include
          echo "Checking for LAPACK"
          ls -al $BLAS_DIR/include
          test -f $BLAS_DIR/include/lapack.h
          ls -al /usr/local/opt/openblas/lib
          test -f /usr/local/opt/openblas/lib/libopenblas.dylib
          echo "CMAKE_CXX_FLAGS=-I$BLAS_DIR/include -L$BLAS_DIR/lib" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$BLAS_DIR" >> $GITHUB_ENV
        fi

    - name: Linux - hdf5, libmatio, vtk, doxygen, and (optionally) OpenBLAS via apt
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt update -q
        if [[ "${{ matrix.blas }}" == "OpenBLAS" ]]; then
          APT_EXTRA=libopenblas-dev
        fi
        sudo apt -yq install liblapacke-dev doxygen graphviz libhdf5-dev libmatio-dev libvtk7-dev lcov $APT_EXTRA

    - name: Configure
      run: |
        source ./build_tools/cmake_configure.sh

    - name: Build
      run: |
        cmake --build build --config ${{env.BUILD_TYPE}}
        ls -al build
        if [ -d build/wrapping/python/openmeeg ]; then
          if [[ "${{matrix.os}}" == 'windows'* ]] && [[ "${{matrix.windows_compiler}}" == 'msvc'* ]]; then
            echo "Copying MSVC pyd file"
            cp -a build/wrapping/python/openmeeg/${BUILD_TYPE}/_openmeeg.pyd build/wrapping/python/openmeeg/
          fi
          ls -alR build/wrapping/python/openmeeg
        else
          echo "No Python wrapping found"
        fi

    - name: Prepare for delocate
      if: startswith(matrix.python, 'python')
      # Let's make it easy for delvewheel to find the stuff it might need
      run: |
        if [[ "${{matrix.os}}" == 'windows'* ]]; then
          cd build
          echo "All:"
          find . -type f -iname "*.dll"
          echo "Data:"
          find . -type f -name "Head1.geom"
          echo "Before:"
          ls -al *.dll || true
          if [[ "${{matrix.blas}}" == "OpenBLAS" ]]; then
            #if [[ "${{ matrix.blas_linking }}" != "static" ]]; then
            if [[ "{{ matrix.windows_compiler }}" != "msvc"* ]]; then
              strip $OPENBLAS_LIB/libopenblas_v0.3.18-gcc_8_1_0.dll
            fi
            cp $OPENBLAS_LIB/libopenblas_v0.3.18-gcc_8_1_0.dll .
            cp $OPENBLAS_LIB/libopenblas_v0.3.18-gcc_8_1_0.dll openblas.dll
            #fi
          fi;
          if [[ "{{ matrix.windows_compiler }}" != "msvc"* ]]; then
            cp /c/Strawberry/c/bin/libquadmath-0.dll .
            cp /mingw64/bin/libgcc_s_seh-1.dll .
            cp /mingw64/bin/libwinpthread-1.dll .
            cp /mingw64/bin/libstdc++-6.dll .
            strip libstdc++-6.dll
            cp /c/Strawberry/c/bin/libgomp-1.dll .
            cp /mingw64/bin/zlib1.dll .
          fi
          if [[ -f "./OpenMEEGMaths/libmatio.dll" ]]; then
            cp ./OpenMEEGMaths/libmatio.dll .
          elif [[ -f "./OpenMEEGMaths/Release/libmatio.dll" ]]; then
            cp ./OpenMEEGMaths/Release/libmatio.dll .
            cp ./OpenMEEGMaths/Release/zlib1.dll .
            cp ./OpenMEEGMaths/Release/hdf5.dll .
          fi
          cp -a *.dll wrapping/python/openmeeg
          echo "After:"
          ls -al *.dll || true
          cd ..
        fi

    - name: Create, delocate, check, install, and test wheel
      if: startswith(matrix.python, 'python')
      run: |
        cd build/wrapping/python
        python setup.py bdist_wheel sdist
        echo "Wheels:"
        ls -alR dist/*.whl
        unzip dist/*.whl -d check
        echo "Contents before:"
        ls -alR check/*
        if [[ ${{matrix.os}} == 'windows'* ]]; then
          PATH="$(cygpath -w $PWD/openmeeg);$PATH" delvewheel show dist/*.whl
          PATH="$(cygpath -w $PWD/openmeeg);$PATH" delvewheel repair -w dist dist/*.whl
        elif [[ ${{matrix.os}} == 'macos'* ]]; then
          delocate-wheel -v dist/*.whl
          delocate-listdeps --all dist/*.whl
        # This build uses a toolchain that is too new, so skip this on Linux
        # else
        #   auditwheel show dist/*.whl
        #   auditwheel repair dist/*.whl
        fi
        rm -Rf check
        unzip dist/*.whl -d check
        echo "Contents after:"
        ls -alR check/*
        twine check dist/*
        pip install dist/*.whl --force-reinstall
        cd ~
        python -c "import openmeeg; print(openmeeg.__version__)"
        pip uninstall -yq openmeeg
        # Now make it so our tests can find the libs
        if [[ ${{matrix.os}} == 'windows'* ]]; then
          echo "PYTHONPATH=$(cygpath -w ${PWD}/build);$PYTHONPATH" >> $GITHUB_ENV
        fi

    - name: Upload wrapped Python lib
      if: startswith(matrix.python, 'python')
      uses: actions/upload-artifact@v3
      with:
        name: wrapping-${{ matrix.os }}_${{ matrix.blas }}_${{ matrix.blas_linking }}_${{ matrix.windows_compiler }}
        path: build/wrapping/python/dist/*.whl

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ctest -C $BUILD_TYPE || ctest -C $BUILD_TYPE --rerun-failed --output-on-failure
