name: PR Checker
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash -el {0}

jobs:

  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    continue-on-error: true
    strategy:
      matrix:
        # Cover the most useful cases most completely
        # TODO: ubuntu-18.04 Python is broken (tests fail)
        # TODO: ubuntu+MKL Python is broken (symbol not found/linking/path issue)
        # TODO: MKL will not build on Windows
        # TODO: MKL status unknown on macOS
        # TODO: Static build broken for OpenBLAS (Could NOT find LAPACK (missing: LAPACK_LIBRARIES))
        os: [ubuntu-20.04, windows-latest, macos-latest]
        blas: [OpenBLAS]
        linking: [dynamic]
        python: [python]
        include:
          # no-python build
          - os: ubuntu-20.04
            blas: OpenBLAS
            linking: dynamic
            python: no-python
          # static build
          #- os: ubuntu-20.04
          #  blas: OpenBLAS
          #  linking: static
          #  python: python
          # ubuntu-18.04 build, but Python tests currently fail so use no-python
          - os: ubuntu-18.04
            blas: OpenBLAS
            linking: dynamic
            python: no-python

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      if: startsWith(matrix.os,'macos') && startswith(matrix.blas,'MKL')
      with:
        auto-activate-base: true
        python-version: 3.6
        channels: conda-forge
        channel-priority: strict

    - name: Environment setup
      run: |
        if [ ${{matrix.linking}} == 'static' ]; then
          echo "STATIC_OPT='-DBLA_STATIC=ON'" >> $GITHUB_ENV
        fi
        if [ ${{matrix.python}} == 'python' ]; then
          echo "PYTHON_OPT='-DENABLE_PYTHON=ON'" >> $GITHUB_ENV
        fi
        if [ ${{matrix.blas}} == 'MKL' ]; then
          echo "BLA_IMPL=-DBLA_IMPLEMENTATION=MKL" >> $GITHUB_ENV
          echo "BLA_PARA=-DMKL_PARALLELISM=sequential" >> $GITHUB_ENV
        fi

    - name: Windows setup
      if: startsWith(matrix.os,'windows')
      run: |
        LF=$(cygpath -w "${PWD}/openblas/lib")
        CF=$(cygpath -w "${PWD}/openblas/include")
        TF=$(cygpath -w "${PWD}/vcpkg/scripts/buildsystems/vcpkg.cmake")
        XF=$(cygpath -w "${PWD}/openblas/include")
        echo "$LF"
        echo "$CF"
        echo "$TF"
        echo "$XF"
        echo "LDFLAGS=-L\"${LF}\"" >> $GITHUB_ENV
        echo "CPPFLAGS=-I\"${CF}\"" >> $GITHUB_ENV
        echo "CMAKE_TOOLCHAIN_FILE=\"${TF}\"" >> $GITHUB_ENV
        echo "CMAKE_CXX_FLAGS=-I\"${XF}\"" >> $GITHUB_ENV
        cat $GITHUB_ENV
        # OpenBLAS direct download (too slow to build using vcpkg)
        curl -LO https://github.com/xianyi/OpenBLAS/releases/download/v0.3.20/OpenBLAS-0.3.20-x64.zip
        unzip OpenBLAS-0.3.20-x64.zip -d openblas
        # vcpkg for matio and hdf5
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        echo "print"
        ls -al ./vcpkg
        which vcpkg
        vcpkg install --triplet x64-windows matio hdf5

    - name: MacOS setup
      if: startsWith(matrix.os,'macos')
      run: |
        brew update > /dev/null
        brew install hdf5 libmatio boost vtk numpy swig homebrew/cask/doxygen graphviz
        if [ ${{matrix.blas}} == "OpenBLAS" ]; then
          brew install openblas
          echo "LDFLAGS=-L/usr/local/opt/openblas/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/opt/openblas/include" >> $GITHUB_ENV
          echo "CMAKE_CXX_FLAGS=-I/usr/local/opt/openblas/include" >> $GITHUB_ENV
        else
          MKL_LIBS=mkl-devel
          if [ ${{matrix.linking}} == 'static' ]; then
            MKL_LIBS=mkl-static
          fi
          conda create -n openmeeg -c intel mkl ${MKL_LIBS} mkl-include
          conda activate openmeeg
          printenv >> $GITHUB_ENV
        fi

    - name: Linux setup
      if: startsWith(matrix.os,'ubuntu')
      run: |
        if [ ${{matrix.blas}} == "OpenBLAS" ]; then
          sudo apt-get update
          sudo apt-get -yq install libopenblas-dev liblapacke-dev
        else
          # There is a mkl version in the official repository for 20.04 but not for 18.04, but it is not up-to-date.
          # Instead rely on intel packages.
          # Get and install the key:
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB |\
                gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" |\
                sudo tee /etc/apt/sources.list.d/oneAPI.list

          # In newer ubuntu >=20.04, mkl is part of the distribution. It can directly be installed with:
          # The syntaxic sugar is because the installation has some interactive configuration part.
          # sudo DEBIAN_FRONTEND=noninteractive apt-get -yq intel-mkl libmkl-full-dev
          # Use this when the ubuntu mkl will be more up-to-date and reliable (in particular in its cmake support).

          sudo apt-get update
          sudo apt-get -yq install intel-oneapi-mkl-devel

          # We need to set some global vars to allow cmake to detect MKL on ubuntu.

          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
        fi

        sudo apt-get update
        sudo apt-get -yq install python3-numpy doxygen graphviz libmatio-dev libvtk7-dev lcov

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration
      # generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        set -x
        cmake -B build \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              ${{env.STATIC_OPT}} \
              ${{env.BLA_IMPL}} \
              ${{env.BLA_PARA}} \
              ${{env.PYTHON_OPT}} \
              -DCMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE }} \
              -DCMAKE_CXX_FLAGS=${{ env.CMAKE_CXX_FLAGS }} \
              -DBUILD_DOCUMENTATION=ON \
              -DTEST_HEAD3=ON

    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ctest -C ${{env.BUILD_TYPE}} || ctest --rerun-failed --output-on-failure
